name: cached_chewie
description: Fork of official chewie with cached_video_player.
version: 1.0.0
homepage: https://github.com/vikram25897/chewie_cached

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter
  provider: ^6.0.1
  cached_video_player: ^2.0.2
  wakelock_plus: ^1.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
